name: python_3.11_jax_0.4.34_cuda_12.6
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aom=3.6.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - cpuonly=2.0
  - cuda-compat=12.6.2
  - cuda-compat-impl=560.35.03
  - exceptiongroup=1.2.2
  - expat=2.6.3
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - grpcio=1.65.5
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - iniconfig=2.0.0
  - jinja2=3.1.4
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libdrm=2.4.123
  - libegl=1.7.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgrpc=1.65.5
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - libre2-11=2023.11.01
  - libsqlite=3.46.1
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markdown=3.6
  - markupsafe=3.0.1
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - p11-kit=0.24.1
  - packaging=24.1
  - pillow=10.4.0
  - pip=24.2
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.11.10
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - re2=2023.11.01
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - six=1.16.0
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.13
  - tomli=2.0.2
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wayland=1.23.1
  - wayland-protocols=1.37
  - werkzeug=3.0.4
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - array-record==0.5.1
      - astunparse==1.6.3
      - attrs==24.2.0
      - chex==0.1.87
      - click==8.1.7
      - cloudpickle==3.0.0
      - dacite==1.8.1
      - datasets==3.0.1
      - dill==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.9.4
      - flatbuffers==24.3.25
      - flax==0.9.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - grain==0.2.1
      - h5py==3.12.1
      - huggingface-hub==0.25.2
      - humanize==4.11.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - importlib-resources==6.4.5
      - jax==0.4.34
      - jax-cuda12-pjrt==0.4.34
      - jax-cuda12-plugin==0.4.34
      - jaxlib==0.4.34
      - git+https://github.com/jax-ml/jax-triton.git  # needs to be current version
      - jaxtyping==0.2.34
      - keras==3.6.0
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - namex==0.0.8
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.3.3
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.0.50
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.77
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.2.3
      - optree==0.13.0
      - orbax-checkpoint==0.7.0
      - pandas==2.2.3
      - platformdirs==4.3.6
      - propcache==0.2.0
      - protobuf==4.25.5
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.9.11
      - rich==13.9.2
      - safetensors==0.4.5
      - scipy==1.14.1
      - sentry-sdk==2.16.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - submitit==1.5.2
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.66
      - termcolor==2.5.0
      - tokenizers==0.20.0
      - toolz==1.0.0
      - transformers==4.45.2
      - triton==3.0.0
      - typeguard==2.13.3
      - tzdata==2024.2
      - wandb==0.18.3
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.14.0
